### PR TITLE
Revert "Merge pull request #723 from matomo-org/pg-2764-retry-mtm-tracking-improvement"

### PR DESCRIPTION
**Pull request by snake14**
This reverts commit 1eed6a4df5a3038111b4ba4d9afc51636bc7689b, reversing changes made to 5cb1114986a4a0b487c2ca2984fbbeea048aef7a.

### Description:

Reverting the MTM changes to try making it work better with _paq.push. The changes are once again causing unexplained data loss.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — APPROVED** [review]
@snake14 All looks good, the only difference I see is this code moved to top from previous code, should we move to bottom again ? Rest all looks good to be merged

Screenshot from 2024-05-14 11-09-12

**Comment by snake14** [comment]
> @snake14 All looks good, the only difference I see is this code moved to top from previous code, should we move to bottom again ? Rest all looks good to be merged

Thanks @AltamashShaikh . I intentionally moved those lines because I didn't think that they were in the right place. It probably doesn't really matter, though. What do you think?

**Comment by AltamashShaikh** [comment]
> @snake14 All looks good, the only difference I see is this code moved to top from previous code, should we move to bottom again ? Rest all looks good to be merged
> 
> Screenshot from 2024-05-14 11-09-12

@snake14 It should not matter :+1:

**Comment by snake14** [comment]
@matomo-org/core-team I just merged this PR. Can we please make sure that it gets tagged for the next 5.1.0 beta release?

**Pull request merged**
