### PR TITLE
etracker wrapper function added for single page applications compatibility

### PR DESCRIPTION
**Pull request by ben-dw**
I have added one further function of etracker (https://www.etracker.com/docs/integration-setup/tracking-code-sdks/tracking-code-integration/dynamische-inhalte-wrapper/).
This function is needed for SPA (single page applications) to trigger pageviews.

### CODE REVIEW

**Comment by tsteur** [comment]
Cheers @ben-dw

**Comment by ben-dw** [comment]
I'm wondering why the changelog 3.13.5 shows that this ticket is integrated. I can't see any changes in the download file for the new matomo version.
@tsteur : Do you have any idea?

**Comment by sgiehl** [comment]
That actually shouldn't be included in the changelog. It was merged to 4.x-dev branch, so it will be included in the first Matomo 4 release and not in any 3.x release. ping @mattab

**Comment by Findus23** [comment]
I think the milestone would need to be ignored here: 
https://github.com/matomo-org/github-changelog-generator/blob/a85da2b0184740ee010f74cf131f4334f9182b5b/src/config.js#L28-L32

**Comment by mattab** [comment]
now deleted the entries from changelog, thanks for the notice @ben-dw 

(also renamed the milestone to Matomo 4.0.0 so it would match my regex I had set: `4.0*`)

**Pull request merged**
