### PR TITLE
[Vue] fix type field v-model

### LINKED ISSUE #444: Variable type shows variable name instead of type
Seems to be a small bug, that the variable **type** is now the same like the variable **name**.
Bildschirmfoto 2022-03-10 um 17 48 11

Matomo Version 4.8

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Fixes #444 

@sgiehl not sure what the process to get this into 4.8 would be.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis  4.8. was already released. So it will be included in the next release

**Comment by diosmosis** [comment]
@sgiehl yes I know, but I don't know how it is intended to be included in 4.8.1 when 4.x-dev TagManager has more changes for 4.9 in it.

**Comment by sgiehl** [comment]
@diosmosis not sure if there will be a 4.8.1 at all. currently none is planned. But actually guess we don't have a process yet for including only certain submodule changes in a bugfix release.

**Comment by diosmosis** [comment]
cc @justinvelluppillai ^

**Comment by justinvelluppillai** [comment]
yes @sgiehl is correct, we don't currently have a process to release only certain plugin changes in a release. It looks like we may need this for #446 also?

**Comment by diosmosis** [comment]
If they are meant to be fixed in a point release then yes for #446. If that's the decision I can create a new branch using the commit in next_release and apply these two PRs there.

**Comment by justinvelluppillai** [comment]
so you would create a branch here with these two PRs, then point this submodule in `next_release` to that branch? Would we then delete the branch here once `4.8.1` is released and lose record of it here? Might need to think about best approach

**Comment by diosmosis** [comment]
@justinvelluppillai good points. Let me know what approach is decided upon and what my place in it is.

**Review by AltamashShaikh — APPROVED** [review]

**Comment by Kixell-NicolasJardillier** [comment]
Any date planned for the new release 4.8.1 ? Because this issue #444 makes Tag Manager unusable

**Comment by sgiehl** [comment]
@Kixell-NicolasJardillier a first release candidate might come up early next week. And the final release approx. a week later.

**Pull request merged**
