### PR TITLE
Add copy button in install code screen, #PG-3520

### LINKED ISSUE #812: UX - Add an icon to copy/paste the Matomo Tag Manager container
Hi Team,

Here is a quick video explaining what would improve easily the UX of Matomo Tag Manager by adding an icon to copy/paste easily the container of Matomo Tag Manager:

https://github.com/matomo-org/tag-manager/assets/28002238/66da5bea-7467-45de-b702-3e6efafe71e1

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Add copy button in install code screen
Fixes: #812 & #PG-3520
Require: https://github.com/matomo-org/matomo/pull/22366

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by AltamashShaikh** [comment]
I added a test for Clipboard copy, but facing same as what we are facing in CrashAnalytics so removed the test.

**Comment by sgiehl** [comment]
@AltamashShaikh Weren't the changes in https://github.com/matomo-org/matomo/pull/22332 meant for making that possible?

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh Weren't the changes in [matomo-org/matomo#22366](https://github.com/matomo-org/matomo/pull/22366) meant for making that possible?

@sgiehl If you checkout this PR and click Install Code under TagManager menu and try to copy the MTM code by clicking copy button, it will not copy anything. On debugging I found out that we need to set focus to allow it to copy.

Screenshot from 2024-07-03 13-35-08

So the changes in [matomo-org/matomo#22366](https://github.com/matomo-org/matomo/pull/22332) adds only the focus to make copy work in modal. Puppeter issue is different.

**Comment by snake14** [comment]
@sgiehl Sadly, https://github.com/matomo-org/matomo/pull/22332 didn't solve the Puppeteer issue as I had hoped, either.

**Review by snake14 — APPROVED** [review]
Looks good. Once I pulled the latest version of core, the button copied the code snippet to my clipboard as expected :+1:

**Review by adamreng — APPROVED** [review]
Yes, works well once I pull core code. Good issue to fix, nice one 👍

**Pull request merged**
