### PR TITLE
Added code to update dimension even when value is not empty or null

### LINKED ISSUE #440: TagManager (variable) values are not reset for tracking, even if they are set to "" or null.
In an SPA, I'm tracking a pageView with a configuration using a bunch of custom dimensions. (Virtual) PageViews are triggered by a custom event, that is pushed into the dataLayer with a bunch of variables.

The problem is, that after setting a variable, e.g. "section" to a value (e.g. "test") in the first dataLayer push, and in a later push, you set it to "" or null, the triggered pageView will nevertheless send "test" as a custom dimension value.

The Debugger correctly shows the variable as empty (""), but the issued requests contains the older value. It seems like the variable is not overwritten by the empty value in the tracker.

Step1: Variable is defined with "TEST1234567" and gets correctly included into the request.
TagManager1b

Step2: Variable is defined with "" (empty string), but old value "TEST1234567" gets included into the request.
TagManager2b

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Added code to update dimension even when value is not empty or null
Fixes: #440

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by heurteph-ei** [comment]
Hi @AltamashShaikh 
Looking at your code, I wonder if this work if you set:
 - (_Boolean_) `false`
 - (_String_) `''`
 - (_Number_) `0`
 - (_String_) `'0'`
 - ...

to the value...

In my opinion you should probably `test !== undefined`

**Comment by AltamashShaikh** [comment]
> Hi @AltamashShaikh Looking at your code, I wonder if this work if you set:
> 
> * (_Boolean_) `false`
> * (_String_) `''`
> * (_Number_) `0`
> * (_String_) `'0'`
> * ...
> 
> to the value...
> 
> In my opinion you should probably `test !== undefined`

@heurteph-ei 
tested above condition
Assume the custom-dimension being used is `test-cd-1`

Case 1: `window._mtm.push({'test-cd-1': 123''});`
Output 1: `test-cd-1:123`

Case 2: `window._mtm.push({'test-cd-1': 'false'});`
Output 2: `test-cd-1:`


Case 1.1: `window._mtm.push({'test-cd-1': 123''});`
Output 1.1: `test-cd-1:123`

Case 2.1: `window._mtm.push({'test-cd-1': ''});`
Output 2.1: `test-cd-1:`


Case 1.2: `window._mtm.push({'test-cd-1': 123''});`
Output 1.2: `test-cd-1:123`

Case 2.2: `window._mtm.push({'test-cd-1': 0});`
Output 2.2: `test-cd-1:0`


Case 1.3: `window._mtm.push({'test-cd-1': 123''});`
Output 1.3: `test-cd-1:123`

Case 2.3: `window._mtm.push({'test-cd-1': '0'});`
Output 2.3: `test-cd-1:0`

**Comment by AltamashShaikh** [comment]
> > Hi @AltamashShaikh Looking at your code, I wonder if this work if you set:
> > 
> > * (_Boolean_) `false`
> > * (_String_) `''`
> > * (_Number_) `0`
> > * (_String_) `'0'`
> > * ...
> > 
> > to the value...
> > In my opinion you should probably `test !== undefined`
> 
> @heurteph-ei tested above condition Assume the custom-dimension being used is `test-cd-1`
> 
> Case 1: `window._mtm.push({'test-cd-1': '123'});` Output 1: `test-cd-1:123`
> 
> Case 2: `window._mtm.push({'test-cd-1': 'false'});` Output 2: `test-cd-1:`
> 
> Case 1.1: `window._mtm.push({'test-cd-1': '123});` Output 1.1: `test-cd-1:123`
> 
> Case 2.1: `window._mtm.push({'test-cd-1': ''});` Output 2.1: `test-cd-1:`
> 
> Case 1.2: `window._mtm.push({'test-cd-1': '123'});` Output 1.2: `test-cd-1:123`
> 
> Case 2.2: `window._mtm.push({'test-cd-1': 0});` Output 2.2: `test-cd-1:0`
> 
> Case 1.3: `window._mtm.push({'test-cd-1': '123'});` Output 1.3: `test-cd-1:123`
> 
> Case 2.3: `window._mtm.push({'test-cd-1': '0'});` Output 2.3: `test-cd-1:0`
> 
> Case 1.4: `window._mtm.push({'test-cd-1': '123'});` Output 1.3: `test-cd-1:123`
> 
> Case 2.4: `window._mtm.push({'test-cd-1': null});` Output 2.3: `test-cd-1:`

**Comment by heurteph-ei** [comment]
Hi again,
>Case 2: `window._mtm.push({'test-cd-1': 'false'});` Output 2: `test-cd-1:`

In my opinion, for test being OK, should output: `test-cd-1:false`

**Comment by AltamashShaikh** [comment]
> Hi again,
> 
> > Case 2: `window._mtm.push({'test-cd-1': 'false'});` Output 2: `test-cd-1:`
> 
> In my opinion, for test being OK, should output: `test-cd-1:false`

@heurteph-ei I tested with `typeof dimension.value !== undefined` and the o/p is still same as the core file is converting it to empty

**Review by snake14 — APPROVED** [review]
Looks alright to me. I was able to override a custom dimension value with a string, int, bool, null, or an empty string without any problems.

**Comment by MatomoForumNotifications** [comment]
This pull request has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/tag-manager-unable-to-reset-custom-dimension-to-null-from-js-variable/53729/3

**Pull request merged**
