### PR TITLE
Added the ability to copy triggers and variables

### LINKED ISSUE #914: Add "Duplicate trigger" functionality
Related to https://github.com/matomo-org/tag-manager/issues/615

Aligned with the ambition to add duplication of MTM containers and tags, this ticket is to add the ability to duplicate triggers.

Suggested UX:
- user can click the duplicate icon on an existing trigger
- user can choose where the trigger is duplicated to (current container, or another container (potentially in another measurable))

### LINKED ISSUE #932: Add "duplicate variable" functionality
Related to https://github.com/matomo-org/tag-manager/issues/615

Aligned with the ambition to add duplication of MTM containers, tags and triggers, this ticket is to add the ability to duplicate variables.

Suggested UX:
user can click the duplicate icon on an existing variable
user can choose where the variable is duplicated to (current container, or another container (potentially in another measurable))

### PR DESCRIPTION
**Pull request by snake14**
### Description:

This PR adds the ability to copy triggers and variables in Matomo Tag Manager. If the trigger or variable references any variables, it will try to reuse any existing variables. If there aren't any matches in the destination container, it will copy the referenced variables as well.

Fixes: #914 #932 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — COMMENTED** [review]
@snake14 Found 1 edge case

1. Copy a trigger
2. It will display the success notification with the URL to navigate
3. Now delete the new copied variable and you will see the notification still stays and it takes you to an empty edit trigger

image


image

**Review by AltamashShaikh — COMMENTED** [review]
@snake14 Should we add a note here, explaining that for customVariables if its referring to any other customVariable, that will not be copied ?

image

**Review by AltamashShaikh — COMMENTED** [review]
@snake14 Looks good to me left 2 comments rest works as expected.

**Comment by snake14** [comment]
> @snake14 Should we add a note here, explaining that for customVariables if its referring to any other customVariable, that will not be copied ?

@AltamashShaikh I don't think that's necessary, because it does copy referenced variables, unless there's a similar one already existing. So, if you're copying to the same container, it reuses the referenced variables. If copying to a different container, it checks if any variables in that container match the referenced variable before making a copy. That's the behaviour for copying containers, tags, triggers, and variables.

Is that not the behaviour that you're seeing?

**Comment by snake14** [comment]
> @snake14 Found 1 edge case
> 
> 1. Copy a trigger
> 2. It will display the success notification with the URL to navigate
> 3. Now delete the new copied variable and you will see the notification still stays and it takes you to an empty edit trigger

Thank you for catching that @AltamashShaikh . I updated the view to hide the success notification when I trigger is deleted. I went ahead and applied the same change for containers, tags, and variables as well.

**Comment by AltamashShaikh** [comment]
> n't think that's necessary, because it does copy referenced variables, unless there's a similar one already existing. So, if you're copying to the same container, it reuses the referenced variables. If copying to a different container, it checks if any variables in that container match the referenced variable before making a copy. That's the behaviour for copying containers, tags, triggers, and variables.

Okay :+1:

**Review by AltamashShaikh — APPROVED** [review]

**Pull request merged**
