### PR TITLE
Add Google Adwords Conversion Tag

### PR DESCRIPTION
**Pull request by pebosi**
Adding Google Adwords Conversion Tag as first try to extend the new tag manager.

### CODE REVIEW

**Comment by duracelltomi** [comment]
Wouldn't it be better to use the native AdWords conversion tracking JS instead of gtag.js here?
Google Tag Manager works in the same way: the native tags load conversion_async.js directly.

gtag.js itself is a mini tag manager container that could be less effective in this case.

**Comment by Findus23** [comment]
The SVG you are using is a bit odd. It embeds one huge png that isn't really needed.

I'd rather use this svg: (cropped from [wikipedia](https://commons.wikimedia.org/wiki/File:Google_AdWords.svg) and optimized with svgo)

```
<svg xmlns="http://www.w3.org/2000/svg" width="130.73" height="130.73" viewBox="0 0 122.56 122.56">
  <path d="M0 61.28V0h122.56v122.56H0z" fill="none"/>
  <path d="M.27 122.23C.27 122.15 40.71.8 40.87.37l.15-.37h40.75l1.6 4.87 20.33 61.09c10.3 30.92 18.72 56.24 18.72 56.27 0 .03-7.08.06-15.73.06-16.93 0-16.47.01-18.65-.7a15.75 15.75 0 0 1-8.95-7.68 3393.5 3393.5 0 0 1-17.54-52.3c0-.44-.25-.14-.51.59-.16.43-4 11.93-8.54 25.56a1798.64 1798.64 0 0 1-8.67 25.67 15.4 15.4 0 0 1-7.42 7.44c-1.77.82-2 .89-3.8 1.22-.9.16-3.61.2-16.71.2-8.6 0-15.63-.03-15.63-.06z" fill="#4285f5"/>
  <path d="M90.22 122.12a15.64 15.64 0 0 1-11.27-8.55 3505.3 3505.3 0 0 1-17.4-52.24A7542.07 7542.07 0 0 1 81.75.54c.05-.18.07-.18.14 0l14.59 43.78 20.2 60.7a899.23 899.23 0 0 1 5.63 17.2c-.13.13-31.38.04-32.1-.1z" fill="#0f9e59"/>
  <path d="M81.07 116.8c-1.81-2.26-2.2-3.16-4.8-11L67.8 80.4a1130.96 1130.96 0 0 1-6.26-19.1c0-.26 19.69-59.54 20.01-60.27l.2-.48c.03-.1.06 26.2.07 58.46 0 32.26 0 58.66-.03 58.66s-.35-.39-.73-.86z" fill="#0a6e3d"/>
</svg>

```

**Comment by Findus23** [comment]
@tsteur https://builds-artifacts.matomo.org/matomo-org/tag-manager/master/8/ seems to be still password protected.

**Comment by tsteur** [comment]
Should work now

**Comment by peterbo** [comment]
Please also implement anonymize IP setting for gtag for (a better chance for) being compliant with GDPR: 
gtag('config', '<GA_TRACKING_ID>', { 'anonymize_ip': true });

**Comment by duracelltomi** [comment]
@peterbo anonymize_ip will not have any effect on the AdWords tracking, it only affects how Google Analytics processes incoming data. One more reason to use the native AdWords conversion_async.js instead of gtag.js

**Comment by peterbo** [comment]
@duracelltomi +1 for using native AdWords Conversion tracking. But if using gtag, it has to be anonymized for users' convenience.

**Comment by tsteur** [comment]
@pebosi do you know how to use AdWords Conversion tracking? I'm not using AdWords myself so not quite sure. Will it be straight forward to change? Or someone has maybe some link to a documentation?

**Comment by peterbo** [comment]
There's quite a good description here: https://tosbourn.com/tracking-adwords-conversion-javascript/

**Comment by tsteur** [comment]
Cheers @peterbo that looks quite straight forward.

**Comment by Findus23** [comment]
@pebosi I hope it's okay if I continue this work in #50. Thanks for starting!

**Comment by tsteur** [comment]
I'll close this PR for now as it is being continued in #50 cheers @pebosi for getting this started 👍

**Comment by tsteur** [comment]
Feel free to comment in #50 or here if anything comes up

**Pull request closed without merging**
