### PR TITLE
Reverting Tag Manager JavaScript Changes

### PR DESCRIPTION
**Pull request by snake14**
### Description:

Reverting Tag Manager JavaScript Changes because they appear to be preventing some tracking requests.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — APPROVED** [review]

**Comment by AltamashShaikh** [comment]
@tsteur Could you have a look once ?

**Comment by tsteur** [comment]
I haven't tested it but looking at the other PRs that looks good 👍

**Comment by utrautmann** [comment]
Hello @snake14 , 
I found this ticket in the Matomo 4.14.2 release notes from 18. April 2023.
What does this ticket mean exactly? I'm asking because my clients are always unsure how to use Tag Manager and the normal tracking script together. So far I advise against sharing.

**Comment by snake14** [comment]
Hi @utrautmann . Sadly, it was reverting the changes I made to make Matomo Tag Manager and the regular tracker work better together. There was apparently a race condition or something that we missed in our testing. So, for now, it's best not to mix the two. If you have customers that need to call `_pag.push()` methods while using MTM, I'd recommend doing so inside of a Custom HTML tag.
We have a new ticket to do some further investigation and see if we can fix the changes that were reverted, but if we're able to fix it, it probably won't be included till Matomo 5.0.0 or later.

**Comment by utrautmann** [comment]
@snake14 : Thank you very much for your answer. I actually don't recommend my clients to use both tracking approaches together. In the past I saw often JavaScript errors in this case.

**Pull request merged**
