### PR TITLE
Fixes custom templates overwrite

### PR DESCRIPTION
**Pull request by ulcuber**
### Description:

Issue with custom templates: https://github.com/matomo-org/tag-manager/issues/148
repeats for another classes.

Extends: https://github.com/matomo-org/tag-manager/pull/149

Fix allows to create another variables with custom templates where templates will not overwrite each other.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — COMMENTED** [review]
@ulcuber Thanks for the PR, changes as such looks good, but do you have any example where its breaking currently and this PR will resolve such issues?

**Comment by ulcuber** [comment]
@AltamashShaikh I am trying to implement Google Tag Manager `jsm` variable alternative using custom template variable. It is nearly same as `CustomJsFunctionVariable` but I am trying to support variables substitution as in https://github.com/matomo-org/tag-manager/issues/212

My suggestion was that `isCustomTemplate` variables should support multiple templates since they could use `loadTemplate`.
Or if it is not appropriate solution that case could be implemented via new method such as `hasMultipleTemplates` to use it instead of class check for `CustomJsFunctionVariable` only.

**Comment by AltamashShaikh** [comment]
@ulcuber I just wanted to have an idea changes looks fine to me.
@tsteur do you have any concerns for this ?

**Comment by tsteur** [comment]
i haven't thought too much about it but this could work well as long as there's no regression for CustomHTML (which seems to be the only other template being a custom template too). 👍

**Review by AltamashShaikh — APPROVED** [review]

**Comment by AltamashShaikh** [comment]
@ulcuber I did my testing and it won't affect `customHTML` so looks good to merge

**Pull request merged**
