### PR TITLE
Added a note and a link to the datalayer documenation

### LINKED ISSUE #541: Add a link to the documentation about the datalayer when the container tracking code is shown
Hi guys,
It would be great to add a link to the datalayer documentation when the container tracking code is displayed.
Without it people may think that the concept of a datalayer does not exist in Matomo Tag Manager.

### PR DESCRIPTION
**Pull request by snake14**
### Description:

It was requested that we add a note with a link to the datalayer documentation when we display the Tag Manager install code, so I went ahead and made that quick change.
Fixes: #541 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — COMMENTED** [review]
@snake14 The current changes looks good but I think we should highlight the dataLayer, otherwise it looks like a extended paragraph

Change this
Screenshot from 2022-08-30 08-02-29

To

Screenshot from 2022-08-30 08-03-22

**Comment by snake14** [comment]
@AltamashShaikh Thank you. That's a good idea. I went ahead and made that change.

**Review by AltamashShaikh — APPROVED** [review]

**Comment by AltamashShaikh** [comment]
@snake14 This file has a merge conflict, you need to merge `4.x-dev` branch into  this branch and keep your local/remote changes and regenerate the vue file

**Comment by snake14** [comment]
@AltamashShaikh Thank you. The conflicts have been resolved.

**Pull request merged**
