### PR TITLE
Converts UI tests to headless chrome

### PR DESCRIPTION
**Pull request by sgiehl**

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis this PR is kind of ready for a review. Some of the tests are randomly failing as the height of the taken screenshots differ in one pixel in height. Tried it with different ways to take the screenshots, but that didn't help. maybe you have another idea to fix that.

**Comment by tsteur** [comment]
@diosmosis do you maybe some time some day to look at this?

**Comment by diosmosis** [comment]
I think I fixed the 1px difference issues, there's at least one other random failure I'm not sure about. One image fails w/ a notification error saying `please supply the idContainer param` (or something similar). I don't want to spend too much time on that so I will probably merge for now.

**Comment by diosmosis** [comment]
@tsteur was able to get a green build for UI tests, but I can't merge PRs on this repo. Can you take a look?

**Comment by tsteur** [comment]
Awesome, thanks @diosmosis . Merging now and you now have also permission to merge here. For some reason was missing there.

**Pull request merged**
