### PR TITLE
[Vue] migrate debugging angularjs controller to vue component

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Changes:
* migrate debugging angularjs controller to vue component

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
Note: UI test failure looks random.

Also, note that this will break existing previews since the HTML appears to be saved on the filesystem. Disabling and enabling the preview fixes it. If needed we can perhaps disable all previews in an update in core.

**Comment by AltamashShaikh** [comment]
> Note: UI test failure looks random.
> 
> Also, note that this will break existing previews since the HTML appears to be saved on the filesystem. Disabling and enabling the preview fixes it. If needed we can perhaps disable all previews in an update in core.

@diosmosis 
We should update it in core, since users might complain that after a recent upgrade Matomo Tag Manager preview is not working.
Also, we can regenerate all the containers or make use of this method `generateContainerIfHasPreviewRelease` to regenerate only when preview enabled.

**Review by AltamashShaikh — CHANGES_REQUESTED** [review]
@diosmosis
We should update it in core, since users might complain that after a recent upgrade Matomo Tag Manager preview is not working.
Also, we can regenerate all the containers or make use of this method generateContainerIfHasPreviewRelease to regenerate only when preview enabled.

**Comment by diosmosis** [comment]
@AltamashShaikh created a core PR here: https://github.com/matomo-org/matomo/pull/18921

**Review by AltamashShaikh — APPROVED** [review]
@diosmosis I just saw this
https://github.com/matomo-org/tag-manager/blob/4.x-dev/TagManager.php#L55

On update we are triggering `regenerateReleasedContainers` so we don't need the change in core, we can keep the plugin changes but no need to make changes in core

**Comment by diosmosis** [comment]
@AltamashShaikh oh I see, that's interesting, I'll close the core PR, nice catch, thanks!

**Pull request merged**
