### PR TITLE
Add close button to close preview debug window, #PG-3550

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Added close button to close preview debug window
Fixes: #PG-3550

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by adamreng — COMMENTED** [review]
Is hiding preview only for current page intended, or should it disable preview mode entirely? Not sure about expected logic. Are we confident this is correct, or need clarification?

**Review by snake14 — APPROVED** [review]
Looks good and worked as expected when I test it :+1:

**Comment by AltamashShaikh** [comment]
> current page intended, or should it disable preview mode entirely? Not sure about expected logic. Are we confident this is correct, or need clarification?

@araichyk We initially thought that we just need to add a close button, as closing the debug mode would require an API call from the browser and I don't think that would be possible.

**Review by adamreng — APPROVED** [review]
Ok, well, it's already completed, so I think it's fine to proceed. If it doesn't meet expectations, we can revisit it later.

Works well for me 👍

**Pull request merged**
