### PR TITLE
[Vue] fix disable preview link in notification no longer works on next_release

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

The sanitization library in core removes attributes like onclick() so the disable preview link click has to be handled a different way. I also added a couple timeouts to tests that will be needed eventually for more Vue changes.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — APPROVED** [review]

**Comment by AltamashShaikh** [comment]
@tsteur @diosmosis 
This looks good, but I noticed our debug option has also stopped working as it was also using onclick

Refer
https://github.com/matomo-org/tag-manager/blob/4.x-dev/templates/previewDebugNotification.twig#L17

**Comment by diosmosis** [comment]
@AltamashShaikh updated

**Comment by AltamashShaikh** [comment]
Screenshot from 2021-11-25 09-50-09

@diosmosis I can see double quotes coming twice

**Comment by diosmosis** [comment]
@AltamashShaikh thanks for catching that, updated one more time

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh thanks for catching that, updated one more time

Looks good now :+1:

**Review by AltamashShaikh — APPROVED** [review]

**Pull request merged**
