### PR TITLE
Allow dynamic height on Tag manager preview

### PR DESCRIPTION
**Pull request by korve**
### Description:

This commit adds a feature that makes the preview bar of the tag manager vertically resizable. It adds a handle with which the user can adjust the height of the bar. The height is also saved in a cookie and restored when reloading the preview site.

I've implemented this because i had massive problems using the preview mode on my daily job. I never had enough real estate to view all tags, triggers etc. I hope this makes the preview bar more usable.

See the following video to get a idea of what this commit provides.

https://user-images.githubusercontent.com/4459994/166812796-fdefb896-59cf-44f1-bcb0-012a634880f1.mp4

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by AltamashShaikh** [comment]
@korve Thanks for the PR seems to work as expected.

**Comment by AltamashShaikh** [comment]
@tsteur Can you have a look once?

**Comment by tsteur** [comment]
@AltamashShaikh  I didn't review the code but from a UX perspective that works for me 👍  nice feature @korve and thanks a lot for the contribution 🎉 .

They only thing I was wondering if should maybe keep a higher min-height of the debug window to make sure some portion of it is always visible? Otherwise people might by accident change the min height, and then it's barely visible and they are thinking it's not shown at all anymore when in fact it is. That could reduce some possible frustrations and support emails.

**Comment by AltamashShaikh** [comment]
@korve can we limit the resize to a certain height to make it always visible ?

**Comment by korve** [comment]
> @korve can we limit the resize to a certain height to make it always visible ?

Yep, i'll look into it.

**Comment by korve** [comment]
I think i've managed to limit the height. Currently it's set to 10% of the viewport.

I had to implement some feature testing to support IE < 11. Specifically `pointerdown` and `pointermove` events are not supported  and also `setPointerCapture` is not supported which allows capturing mousemove events outside the browser window.

**Review by AltamashShaikh — APPROVED** [review]
@korve Looks good :+1:

**Pull request merged**
