### PR TITLE
Allows user with publish_live_container capability to publish a container without use_custom_template capability, #PG-3899

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Allows user with publish_live_container capability to publish a container without use_custom_template capability
Fixes: #PG-3899, #893

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by snake14 — CHANGES_REQUESTED** [review]
The changes look good. However, I receive an error when I try to publish a new version as a write user that only has publish capability without custom templates ability:
image

image

Looks like that's from here: https://github.com/matomo-org/tag-manager/blob/e0556b528eb1bbc0237a7ec43ef7929a4c636485/API/Import.php#L98

**Review by snake14 — APPROVED** [review]
Functional testing passed with most recent changes. I was able to publish a new version with only write and publish permissions :+1:

**Comment by PeteTrombone** [comment]
When will this finally be implemented? We urgently need the fix.

**Comment by snake14** [comment]
Hi @PeteTrombone . It looks like the changes from this PR were included in the Matomo 5.2.0 release.

**Comment by PeteTrombone** [comment]
Hi @snake14 
we installed version 5.2.1 and tested it. It doesn't work quite as expected.

Before the whole changes, it was possible to publish containers for Dev and Staging only with write permission (Tag Manager: Write). 
Now, in addition to write permissions, a user also needs the right to publish live containers (Tag Manager: Publish Live Container) in order to publish a container (Dev, Staging and Live).
That's not what we need!
A user should also be able to publish a container on Dev or Staging only with write permissions.

We don't want to give every user the right to publish a live container. That's too high a risk for us.

**Comment by snake14** [comment]
Hi @PeteTrombone . Another option is to give the user custom template capability.
image

Sadly, in order to create a version and publish, one of those two permissions is required. This is mainly because publishing inherently involves handling custom templates.

**Comment by PeteTrombone** [comment]
Hi @snake14 
As I wrote above, I just want the rights to be the way they were before version 5.1.0.
With version 5.1.0, issue [#784](https://github.com/matomo-org/tag-manager/issues/784) was "fixed". This removed the right to publish containers to Dev and Staging from users with write permissions. This should be reversed.
This was a fix that made things worse.

**Comment by AltamashShaikh** [comment]
@PeteTrombone Can you please create a new issue for this ? This way we can highlight the issue to our product team and they can decide accordingly.

**Pull request merged**
